name: rsk
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  image_picker: ^1.0.1
  ionicons: ^0.2.2
  signature: ^5.4.0
dev_dependencies:
  build_runner:

flutter_launcher_icons:
  android: "rsk"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  flutter_test:
    sdk: flutter
  freezed: null

flutter:
  assets:
    - assets/icon/
  uses-material-design: true
